spring.application.name=projetSpring

spring.datasource.url=jdbc:mysql://localhost:3306/pfa_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

ollama.url=http://localhost:11434
ollama.model=gemma2:2b

jwt.secret=pfaManagerSecretKey2024VeryLongAndSecureKeyForJWT
jwt.expiration=86400000

server.port=8085